apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  namespace: default
  labels:
    app: netflix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-app
  template:
    metadata:
      labels:
        app: netflix-app
    spec:
      containers:
      - name: netflix-app
        image: mujju752/netflix-app:{{IMAGE_TAG}}
        ports:
        - containerPort: 3000
        env:
        - name: TMDB_KEY
          valueFrom:
            secretKeyRef:
              name: netflix-secret
              key: TMDB_KEY
