apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: netflix-alerts
  labels:
    release: monitoring
spec:
  groups:
    - name: netflix.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{pod=~"netflix-app.*"}[2m])) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU Usage"
            description: "Netflix app CPU > 0.5 cores"

        - alert: PodCrashLooping
          expr: increase(kube_pod_container_status_restarts_total{pod=~"netflix-app.*"}[10m]) > 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "CrashLoop Detected"
            description: "Netflix app pods restarting"
