{{- if .Values.secrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: netflix
spec:
  encryptedData:
    TMDB_KEY: {{ .Values.secrets.TMDB_KEY }}
{{- end }}
