apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: netflix-alerts
  namespace: default
spec:
  groups:
  - name: netflix-app-alerts
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 5
      for: 1m
      labels:
        severity: warning
      annotations:
        description: "High 5xx error rates on Netflix app"
